### ISSUE TITLE
trying to get this working on kubernetes

### ISSUE THREAD

**Issue by sokoow** [farmOS/farmOS#132]
Hey All,

Trying to get farmos working on kubernetes, here's some minimal manifests:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: farmos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: farmos
    spec:
      containers:
      - name: farmos
        image: farmos/farmos:7.x-1.x
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: "POSTGRES_USER"
            value: "farmos"
          - name: "POSTGRES_PASSWORD"
            value: "farmos"
          - name: "POSTGRES_DB"
            value: "farmos"
          - name: "FARMOS_DEV"
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: farmos-svc
spec:
  selector:
    app: farmos
  ports:
  - name: web
    port: 80
---
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: farmos
  annotations:
   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: farm.XXX.net
    http:
      paths:
      - path: /
        backend:
          serviceName: farmos-svc
          servicePort: 80
```

Here's some challenges I've come across, hopefully you can help here:

1. The docker container seems to be reinstalling all modules again and again - is it possible to build a docker image which is a step after that (so has modules pulled in and is starting fast) ?
2. What would be a required persistence volume for drupal configs ? There probably is a file with db settings and so on, where is it ?
3. How would one set proper base url and where ? I'm getting lots of mixed content warnings when on tls... 

Sorry if these questions are silly - nice product and keep it going! :D Greetings
