### ISSUE TITLE
Feature request: configurable PHP upload/post size limit on Docker containers

### ISSUE THREAD

**Issue by realcanadrian** [farmOS/farmOS#310]
It would be useful if there were a way to configure the max post size and max upload size in PHP for the Docker containers. Perhaps this could be an environment variable? Or the PHP config file could be exposed via a volume?

Thanks!

**Comment by symbioquine** [comment]
This is already easily configurable out-of-the-box - though not super obvious without an example...

**docker-compose.yml**
```yaml
  www:
    depends_on:
      - db
    image: farmos/farmos:7.x-1.3
    volumes:
      - './sites:/var/www/html/sites'
      - './php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini'
    ports:
      - '8080:80'
```

**php-custom.ini**
```ini
upload_max_filesize = 10M
post_max_size = 10M
```
