### ISSUE TITLE
Replace Docker build with buildx for multi environment support?

### ISSUE THREAD

**Issue by and712** [farmOS/farmOS#339]
as stated by @mstenta in "Run on Rasperry Pi via Docker" https://github.com/farmOS/farmOS/issues/58 it is not possible to use the docker hub image on Raspberry Pis. 
Also described in the ticket is the still functional workaround (only the folders changed). 

In https://www.drupal.org/project/farm/issues/3162767 and https://www.drupal.org/project/farm/issues/3162686 @mstenta also mentions the changes for the build process for farmOS 2.0
It seems like the change to buildx pipelines with Github is easy, because there is a Action in Github: https://github.com/marketplace/actions/docker-buildx 

I never tried to build a docker image or used Github Actions bevor and got a semi working PoC in ~1h. 
Whats missing / not working: 

- publishing on docker hub (didnt try till now)
- run 'docker-entrypoint.sh' (Didnt really get what this script is doing)

Now my questions are: Is it even useful to update the build process for 1.0 or is it better to wait for 2.0 
(Probably also depends on when 2.0 is released ;) ) and is it even a good idea to use buildx? 

````
name: Test 7.x-1.x Docker and Drush Make builds
on:
  push:
    branches:
      - '7.x-1.x'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set FARMOS_BRANCH environment variable
        run: echo ::set-env name=FARMOS_BRANCH::${GITHUB_REF:11}
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=false" \
            --build-arg FARMOS_REPO=https://github.com/${GITHUB_REPOSITORY} \
            --build-arg FARMOS_BRANCH=${FARMOS_BRANCH} \
            --file ./docker/dev/Dockerfile ./docker/dev
````
