### ISSUE TITLE
Map ui is unreadable on dark mode

### ISSUE THREAD

**Issue by wotnak** [farmOS/farmOS#641]
**Describe the bug**
With the dark mode enabled in [Gin theme settings](https://www.drupal.org/docs/contributed-themes/gin-admin-theme/specific-settings-within-gin), map ui is not really readable. The text color is changed to a bright gray like on the rest of the page, but the background remains white, which makes it really hard to manage layers.

**To Reproduce**
1. Enable dark mode in the Gin theme settings `/admin/appearance/settings/gin`.
2. Go to the main dashboard to display a map.
3. Text color on the map ui is really close to the background color, which makes it practically unreadable.

**Expected behavior**
Background color of the map ui elements should change to dark one when dark mode is enabled.
Applying following styles makes it much more readable:
```css
.gin--dark-mode .farm-map .ol-control,
.gin--dark-mode .farm-map .ol-scale-line {
    background-color: rgba(var(--gin-bg-app-rgb),.25);
}
.gin--dark-mode .farm-map .ol-control:hover {
    background-color: rgba(var(--gin-bg-app-rgb),.6);
}
.gin--dark-mode .farm-map .ol-control button {
    background-color: rgba(var(--gin-bg-app-rgb),.8);
}
```

**Screenshots**
Current behaviour:
![image](https://user-images.githubusercontent.com/52507690/220160967-4d6316c9-ba80-4b86-bbcd-c360604af9d9.png)

After applying styles provided above:
![image](https://user-images.githubusercontent.com/52507690/220161044-06d31745-0939-43cd-b109-4c3aeec9b354.png)
