### ISSUE TITLE
Exception: Serialization of 'SimpleXMLElement' is not allowed

### ISSUE THREAD

**Issue by followmeongitlab** [farmOS/farmOS#896]
**Describe the bug**
When trying to import a KML or KMZ file, I receive the error:

```
Exception: Serialization of 'SimpleXMLElement' is not allowed in serialize() (line 14 of /opt/drupal/web/core/lib/Drupal/Component/Serialization/PhpSerialize.php).
```

**To Reproduce**
1. Go to `Setup > Import > KML Import`
2. Click on `Browse` and select the KML file
3. Select `Property` from Default Land Type drop-down
4. Click `Parse`
5. See error

**Expected behavior**
I am expecting this to successfully import a KML file to use as a new land asset.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: FireFox
 - Version 132.0.1

**Additional context**
The KML file in question was an export of a single parcel from VT's parcel maps.
https://geodata.vermont.gov/datasets/09cf47e1cf82465e99164762a04f3ce6_0/explore

This is a new install (I am a fresh FarmOS user) using Docker/Docker Compose on a local server. Only modifications I've made to settings so far have been to enable file import.

 The docker-compose.yml:
 ```
 version: "3"
services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - '/data/farmos/db:/var/lib/postgresql/data'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
  farmos:
    depends_on:
      - db
    image: farmos/farmos:3.3.1
    volumes:
      - '/data/farmos/sites:/opt/drupal/web/sites'
    ports:
      - '3333:80'
    restart: always
```

Happy to provide any other information that may be useful in identifying a cause/resolution.
