### ISSUE TITLE
Deploying the latest release with docker compose fails

### ISSUE THREAD

**Issue by kracel** [farmOS/farmOS#933]
**Describe the bug**
Deployment with docker compose fails with the latest version (3.4.1)
After deployment, going to the first time setup, connecting to the db works fine, but when trying to install modules it fail with a AJAX  error (tried default modules, all modules, default plus some random modules)

The error is:
```
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?rewrite=ok&profile=farm&langcode=en&id=2&op=do_nojs&op=do
StatusText: OK
ResponseText: TypeError: Drupal\simple_oauth\Service\KeyGeneratorService::generateKeys(): Argument #1 ($dir_path) must be of type string, false given, called in /opt/drupal/web/profiles/farm/modules/core/api/farm_api.install on line 61 in Drupal\simple_oauth\Service\KeyGeneratorService->generateKeys() (line 65 of /opt/drupal/web/modules/simple_oauth/src/Service/KeyGeneratorService.php).
```
Reading the error, assumed something with OAuth and browsed trough the releases.
Found an update to OAuth in 3.3.3 and decided to try the previous release to this update (3.3.2)
Everything went as it should, super smooth (But there is a big red message telling me to update).

**To Reproduce**
1. Create a docker compose based on the instructions from the github page
2. Deploy with latest, or 3.4.1 tag
3. Go trough the setup wizard

**Expected behavior**
Installation succeds

**Server**
 - LXC container running arch

**Additional context**
Docker compose 
```
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm
    volumes:
      - './farmos/db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    restart: unless-stopped

  www:
    image: farmos/farmos:3.4.1
    container_name: farmos
    volumes:
      - './farmos/sites:/opt/drupal/web/sites'
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - db
```
